// This file was generated by the generate_boot_screen Haiku build tool.

static const int32 kSplashLogoPlacementX = 50;
static const int32 kSplashLogoPlacementY = 50;
static const int32 kSplashIconsPlacementX = 50;
static const int32 kSplashIconsPlacementY = 50;

static const uint16 kSplashLogoWidth = 10;
static const uint16 kSplashLogoHeight = 10;
#ifndef __BOOTSPLASH_KERNEL__
static uint8 kSplashLogo24BitCompressedImage[] = {

	};
#endif

static const uint16 kSplashIconsWidth = 308;
static const uint16 kSplashIconsHeight = 80;
#ifndef __BOOTSPLASH_KERNEL__
static uint8 kSplashIcons24BitCompressedImage[] = {

	};
#endif

#ifndef __BOOTSPLASH_KERNEL__
static const uint8 k8BitPalette[] = {

	};

static uint8 kSplashLogo8BitCompressedImage[] = {

	};

static uint8 kSplashIcons8BitCompressedImage[] = {

	};

#endif

